application: pixelcycle
version: draft-compress
runtime: go
api_version: go1

handlers:
- url: /
  script: _go_app

- url: /m[0-9]+
  script: _go_app

- url: /gif
  script: _go_app

- url: /(.*\.(css|js|js\.map))
  static_files: \1
  upload: (.*\.(css|js))

- url: /(packages/pixelcycle2/src/.*\.dart)
  static_files: \1
  upload: /packages/pixelcycle2/src/.*\.dart

- url: /_load
  script: _go_app

- url: /_share
  script: _go_app
