application: pixelcycle
version: draft-confirm
runtime: go
api_version: go1

handlers:
- url: /
  script: _go_app

- url: /m[0-9]+
  script: _go_app

- url: /gif/[0-9]+
  script: _go_app

- url: /json/[0-9]+
  script: _go_app

- url: /save
  script: _go_app

- url: /(.*\.(css|js|js\.map))
  static_files: \1
  upload: (.*\.(css|js))

- url: /(packages/pixelcycle2/src/.*\.dart)
  static_files: \1
  upload: /packages/pixelcycle2/src/.*\.dart

